blank_issues_enabled: true
contact_links:
  - name: GH discussions
    url: https://github.com/Feodor0090/nmania/discussions
    about: Ask for help or propose an idea.
  - name: TG chat
    url: https://t.me/nnmidletschat
    about: Community of nnproject software. You can ask here for help or learn about other applications.
