name: Release CI
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup
        run: sudo dpkg --add-architecture i386 && sudo apt update && sudo apt-get install gcc-multilib libxt6:i386
      - name: Build
        run: cd ${{ github.workspace }} && chmod +x ./build.sh && RELEASE=1 ./build.sh
      - name: Upload jar
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ github.workspace }}/jar/
